### ISSUE TITLE
被查单词的容器为overflow:scroll时，解释框定位有问题

### ISSUE THREAD

**Issue by wizcabbit** [jinntrance/shanbay-crx#18]
被查单词的容器为overflow:scroll时，解释框top定位计算结果为被查词到父容器顶部的距离，这个距离大于或等于被查词窗口顶部的距离。

因此使用这个距离时，解释框定位出现问题。
测试网址：http://toefl.kaomanfen.com/ 或其他TPO联系网站，经常使用overflow:scroll

待修改：shanbay.js: getSelectionOffset()

**Comment by jinntrance** [comment]
多谢反馈。 
我这面得空看看。或者您那面提交一PR也可。

**Comment by jinntrance** [comment]
最子一层使用jquery的position()计算跟跟父元素左上的相对距离。
