### ISSUE TITLE
添加几个快捷键，支持切换到共享笔记和添加笔记

### ISSUE THREAD

**Issue by jinntrance** [jinntrance/shanbay-crx#22]

**Comment by halfer53** [comment]
我的设想是，按y打开共享笔记，然后可以分别按快捷键1,2,3来“喜欢”第一，第二，第三个笔记，这样笔记就会自动加入到“我的笔记”中。

**Comment by jinntrance** [comment]
嗯 这倒是挺好的。

不过123 会不会离得远，操作起来不方便？

**Comment by jinntrance** [comment]
已经添加Y 打开用Y户共享笔记，Z 自己创建笔记（作Z笔记）。

讨论后暂定：考虑到减小扇贝服务器的负担，如果能查看到用户分享的top 3 的笔记，就不再添加快捷键重复收藏到自己的笔记。
