### ISSUE TITLE
有没有可能增加其他词典来源？

### ISSUE THREAD

**Issue by HalbertDong** [jinntrance/shanbay-crx#26]
比如OALD，没有API的，但是网页可以很方便地搜索得到结果。

**Comment by jinntrance** [comment]
可以啊。
从内容初步看来，OALD 也还蛮全的。英文释义，派生等都能用到。

要是您也能参与开发就再好不过了，也可以尽量快的把这个功能上线^^

**Comment by Hasset** [comment]
是的，只需要加入OALD的解释，派生、词根、词源等等都包含在内。
我是个业余码农，愿意帮忙，你需要哪些帮助呢？

**Comment by jinntrance** [comment]
主要就是js和jquery编程。
我这面先重构一下，加些注释和把这种切换词源的接口整理出来，酱紫后续添加其他词源也就方便多了。
然后你那面再解析一下OALD 上的派生词根词源等到某个数据结构里就可以了。

**Comment by jinntrance** [comment]
@Hasset 不好意思，这个代码重构拖了太久。 如果你还有兴趣添加OALD，请参考这个 [README](https://github.com/jinntrance/shanbay-crx/blob/master/js/dictionaries/README.md)

**Comment by jinntrance** [comment]
重构代码，方便添加词典。
