### ISSUE TITLE
"双击单词查义" 未即时生效

### ISSUE THREAD

**Issue by HalbertDong** [jinntrance/shanbay-crx#27]
打开"双击单词查义"   是   否
这个关了似乎起不到作用QAQ

**Comment by jinntrance** [comment]
关掉双击单词查义后，你那面是一直不起作用，还是只是第一次不起作用？ 
我这面测试的是第一次不起作用，后续就一直可用了。

**Comment by Hasset** [comment]
没注意，反正总是现在每天都会出现。。。

**Comment by jinntrance** [comment]
按理说保存成功后不会出现这种问题。你在设置页面，点击保存后，提示的是保存成功还是保存失败了？

**Comment by Hasset** [comment]
保存成功

**Comment by jinntrance** [comment]
你是Chrome Store 上安装的最新版本 1.12.10 么？

**Comment by Hasset** [comment]
刚刚测试了一下，我发现是这样：
关闭以后，打开包含英文的页面。第一次双击英文单词，会出现，再点就没有了。

**Comment by Hasset** [comment]
1.12.11

**Comment by jinntrance** [comment]
由于Chrome 的机制以及数据存储的隔离，外加考虑响应的即时性。之前设计得就是设置生效后，新开网页就是最新设置，就网页需要操作一次后才会更新设置。
这一块儿后续可以再改进一下。
