### ISSUE TITLE
无法使用鼠标右键“在扇贝网中查找XX”功能

### ISSUE THREAD

**Issue by 4wheels** [jinntrance/shanbay-crx#40]
全新安装此插件，使用插件默认设置。可以双击查词，但选择英文词组后右键选择“在扇贝网中查找XXX”功能后没有反应。请问这可能是什么原因，如何解决此问题？

可能有用的信息：
OS: Windows 10 x86
Chrome Version: 47.0.2526.80 m
使用的插件: 有道词典Chrome支持插件，Adblock Plus，SwitchyOmega等

截图：
![image](https://cloud.githubusercontent.com/assets/5765843/11776126/9055915c-a27f-11e5-9f3c-81d8aa03618d.png)

最后对作者持续的付出表示感谢！

**Comment by jinntrance** [comment]
抱歉，回覆晚了。我這面暫時沒辦法復現，不知你現在是否還有此問題？登錄扇貝後也有此問題不？

有一種情況是，查不到這個詞組（因爲用的是扇貝網的詞庫）然後沒有給提示。這個是交互設計得不好，待改進。

**Comment by jinntrance** [comment]
未登录扇贝网导致不出词，查询过程中提示用户登录扇贝网。
