### ISSUE TITLE
使用 React 重构？

### ISSUE THREAD

**Issue by sskyy** [jinntrance/shanbay-crx#41]
你好，我非常喜欢你做的这款插件。想要参与进来，但是翻了一下代码有点不知道怎么下手好，是否考虑用 React + ES6 重构下？

**Comment by jinntrance** [comment]
代码都是js 和 jQuery，也有部分的HTML/CSS。React + ES6 我本人倒不熟。

重构原来的代码，我也很赞成。因为也是最先学js 的时候写的代码，写得不好。

不过可能还需要在这两个方面做balance：简洁的代码 vs 这个扩展的打包大小。
