### ISSUE TITLE
可不可以参考chazd或者translt，允许把窗口显示在右上方？

### ISSUE THREAD

**Issue by qwIvan** [jinntrance/shanbay-crx#42]
https://github.com/ververcpp/ChaZD
https://github.com/GDG-Xian/crx-transit

**Comment by jinntrance** [comment]
我看了这两个扩展。

您的意思是，查词后的释义窗口，可以像Chrome Notifications 一样显示在右上方么？

现目前没有放到右上方出于一下几个方面考虑：

- Chrome Notifications 的样式比较单一，不好加buttons。
- 这个扩展是给扇贝用户做的。那么如果扇贝用户忘记这个词的释义了，或者想查看例句等，需要进一步的操作，如果展示得跟光标太远，对用户来说就会很不方便。


您可以讲讲您给出上面建议的考虑，大家一起探讨一下~

**Comment by qwIvan** [comment]
并不是，是用css把div固定在右上方悬浮，相对浏览器窗口定位

**Comment by qwIvan** [comment]
![2016-02-28 19 53 02](https://cloud.githubusercontent.com/assets/7613160/13379014/ef178e28-de54-11e5-834a-c20d8f9f93fd.png)

**Comment by jinntrance** [comment]
考虑到尽量让用户的操作更便捷，就近显示popup。

如果popup 计算出来的位置出现问题 #46  ，可以考虑放在整个页面的右上角。

**Comment by jinntrance** [comment]
@qwIvan 抱歉，我对CSS 不是太熟悉，后续我有空再看看你推荐的两个扩展，后面添加进来。
