### ISSUE TITLE
希望背单词时笔记部分默认显示共享笔记

### ISSUE THREAD

**Issue by Latias94** [jinntrance/shanbay-crx#43]
扇贝默认显示“我的笔记” 不加就是空白 看别人的笔记还要去点，能默认显示就好了。

**Comment by jinntrance** [comment]
现有[所有快捷键列表 ](http://josephjctang.com/shanbay-crx/#shortcuts) 里，背单词时键盘按Y 就可以查看用户分享笔记。

你的意思是不是，没有自己的笔记的时候，默认显示别人分享笔记？

**Comment by Latias94** [comment]
噢对的 能默认最好
