### ISSUE TITLE
划词有的页面还是取不出来呀，希望能够改善下

### ISSUE THREAD

**Issue by ACBingo** [jinntrance/shanbay-crx#46]
比如在我现在的这个页面
http://developer.android.com/reference/android/widget/ImageView.html
Class Overview等描述的文字都能正常打开划词窗口，但是在下面的表格里面却识别不出来了，然而谷歌官方的可以正常使用，强烈希望改善下这个呀。
或者加入一个点击icon（类似于谷歌官方的那个翻译插件）提供查询窗口和加入生词按钮

**Comment by jinntrance** [comment]
popup 定位问题。table 内查询，计算位置会有偏差导致。

**Comment by Macer3** [comment]
如果在浏览器里浏览本地的pdf文件时也能划词查询就好了，不知道原理上有什么不同，现在的版本不能。浏览器里也有少数地方不能查

**Comment by jinntrance** [comment]
@Macer3 原理有一些不同。据我目前知识，Chrome 处于安全考虑，目前查词时只能让这个扩展跑在后台的background page 负责所有页面的查词请求，然后再回传给对应的tab（每一个html 的页面都能有一个id 值，但是pdf 页面没有这个id 值），有对应ID 值就能回传对应到确切的tab 弹出，不然就没办法找到对应的tab。所以目前pdf 还不好做。
