### ISSUE TITLE
突然就不能用啦

### ISSUE THREAD

**Issue by Yct** [jinntrance/shanbay-crx#47]
今天早上还能用，中午就突然不能用啦
所有功能都扑街。。
加油加油

**Comment by jinntrance** [comment]
请问是哪些功能不可用了？ 

- 我这面任意网页查词还可用。
- 背单词的时候部分快捷键似乎不可用了。
- 词根派生似乎不可用了。

看样子是网页改版造成的，得后续有时间了再check 和和再修复了。

**Comment by irmowan** [comment]
同，背单词快捷键失效。突然就不习惯了。

**Comment by libing8964** [comment]
chrome版本（Version 51.0.2687.0 m ），电脑（（win7x64）），升级Chrome之后就无法使用这个插件了，不知为何，求解决，多谢楼主所做的这个插件，很大的提高了效率，建议楼主可以根据网友建议开发出更多功能以及尝试收费。

哪些功能不能用？词汇派生和词根功能不能用了，以及并不能显示Google图片搜索和百度图片搜索了。

**Comment by WaltzZ** [comment]
昨天更新了chrome之后词根派生失效

**Comment by jinntrance** [comment]
后续大家升级到1.13.3 再看看呢。 http://josephjctang.com/shanbay-crx/#安装

**Comment by WaltzZ** [comment]
已经可以使用了 感谢

**Comment by jinntrance** [comment]
@libing8964 多谢建议。
确实有好些朋友给了建议，但都没精力去开发完善。如果得到更多的人鼓励，兴许还有动力一些。收费可能不合适，因为不好定价，而且我感觉用这个扩展的还有很多学生。小额捐赠应该可以考虑。
