### ISSUE TITLE
若可以,请增加忽视站点或域名的功能,谢谢.

### ISSUE THREAD

**Issue by xjdata** [jinntrance/shanbay-crx#49]
若可以,请增加忽视站点或域名的功能,谢谢.
做开发的时候本地页面不需要翻译功能,但是双击什么的经常出现,有些不方便,如果可以,请考虑增加护士站点的功能.谢谢.

**Comment by jinntrance** [comment]
我也做web 开发，但不怎么双击。也就没有你说的这个问题。

你双击是你开发的时候个人的习惯还是也是需要双击测试一些功能？如果你要双击测试，倒是可以先关闭这个扩展。

另外个人觉得这个 feature 面向的受众太有限，先关闭。 @xjdata 如果你觉得这个功能应用面也较广，麻烦解释一下，后面再打开。

也欢迎再提其他 features 改进建议~
