### ISSUE TITLE
在某些页面，翻译后的结果会在页面最底下

### ISSUE THREAD

**Issue by cenxun** [jinntrance/shanbay-crx#54]
比如在 `http://stackoverflow.com/` 选中翻译后结果再最底下，要拉到底才能看见......

![qq 20160811090718](https://cloud.githubusercontent.com/assets/5516946/17576235/1d198c52-5fa3-11e6-8f13-c9e8411316d2.jpg)

相关版本
Chrome `52.0.2743.116 m`
扇贝助手增强版 `1.13.4`

**Comment by jinntrance** [comment]
是在页面哪个地方取词会出现这种情况呢？ 我这面看到的是正常的。
<img width="1196" alt="取词截图" src="https://cloud.githubusercontent.com/assets/2414660/17591886/acaecb74-6012-11e6-9f67-ed7554a6278b.png">

**Comment by jinntrance** [comment]
正文table 内元素位置计算出错。

duplicate of #46
