### ISSUE TITLE
Quora 首页的详细查看不会弹出，HDU_OJ的弹出位置不对

### ISSUE THREAD

**Issue by MJRT** [jinntrance/shanbay-crx#55]
![1](https://cloud.githubusercontent.com/assets/17826582/17621867/11b0d966-60c9-11e6-81c7-043029f76a16.png)
![2](https://cloud.githubusercontent.com/assets/17826582/17621868/11b65756-60c9-11e6-9a51-5dc5f082a7ac.png)

**Comment by jinntrance** [comment]
第一问题原因是扇贝的popup 被quora 自己的popup覆盖掉了，新版本会修复这个问题。
第二问题应该跟这个 #46 一样， table 内查询，计算会有偏差。
