### ISSUE TITLE
在 macOS 上一直占用5%的 CPU

### ISSUE THREAD

**Issue by ypwhs** [jinntrance/shanbay-crx#58]
只要打开 chrome 且开启扇贝助手，coreaudiod 进程会在 macOS 上一直占用5%的 CPU，累计消耗的 CPU 比操作系统还要多。在扩展程序关闭扇贝助手后 coreaudiod 进程的 CPU 占用率会跌至0%。

操作系统：macOS 10.12 (16A323)
Chrome 版本：53.0.2785.143 (64-bit)

![image](https://cloud.githubusercontent.com/assets/10473170/19116995/0b08e238-8b4a-11e6-8030-21f982465871.png)

**Comment by jinntrance** [comment]
多谢反馈。

我也纳闷不知道什么时候开始Mac 电池越来越不耐用了😹

看了。观测是依赖的旧版单次发音库的bug https://github.com/goldfire/howler.js  ，更新到最新版本后目前发现没有这个问题了。
