### ISSUE TITLE
希望添加单复数、时态、常用短语

### ISSUE THREAD

**Issue by linksgo2011** [jinntrance/shanbay-crx#64]
作者这个插件非常棒，但是一直在背单词的时候发现一个问题，就是仅仅关注单词原型非常不利于应用单词，希望能添加单复数和时态和常用短语功能。谢谢

**Comment by linksgo2011** [comment]
我已经添加了这些功能，并提交了一个pull request :)

**Comment by jinntrance** [comment]
多谢 @linksgo2011 

我这面给你测试通过就可以会重新发布一个新版本~

**Comment by jinntrance** [comment]
再测试看了看。
是否可以增加设置项目，隐藏新加的两项呢？ 一个原因是多数单词都比较规则，不一定多数人都需要单词变形。
另外，如果不能展示变形的时候，这个区域是否可以不显示？

**Comment by linksgo2011** [comment]
@jinntrance 谢谢，时间仓促，我再读下你的配置相关的逻辑，下个提交加上来吧。过年刚好有时间

**Comment by linksgo2011** [comment]
@jinntrance  另外有个建议，建议弄个featuers 的文件夹，大家把自己的feature 开个新文件提交，这样可能耦合要小一点。或者弄个包管理工具也不错 :)

**Comment by jinntrance** [comment]
@linksgo2011 多谢建议。我回头把也重构一下并加一些注释方便以后大家加feature~
