### ISSUE TITLE
查询单词后直接添加到生词本

### ISSUE THREAD

**Issue by jinntrance** [jinntrance/shanbay-crx#71]
reported by Yangjunxiong

得考虑增加配置项，因为以下几种情况用户不需要添加到生词本。
- 只是想查看这个单词意思，不需加入生词本。
- 用户误操作。

**Comment by jinntrance** [comment]
reported by Qinsi Liang:

查询单词时，自动发音、自动加入生词本（或者设置里有这个选项也好）

**Comment by qins** [comment]
每天查词量大约在50到200（如果读外文）。其中大多数都需要加生词本。
单个单词分别加的话，重复操作太多了。

误操作一般不多，这有个解决办法：
设置里可选 是否 自动加生词本
否：保留目前机制不变
是：自动加，但上面的“加生词本”变为“删除生词”或者“我认识”，“我熟悉”

很多年前就有这个需求，全平台的查词自动记生词本，遇到这个不得不说一句 perfect！

**Comment by jinntrance** [comment]
目前扇贝没有提供我熟悉的接口，解决方法：
1. 默认自动加入生词本，不再显示“我忘了”；
2. 默认不自动发音；
3. 对自动加入生词本、自动发音添加设置。
