### ISSUE TITLE
安装后google搜索， 会自动跳转天猫

### ISSUE THREAD

**Issue by Andy1984** [jinntrance/shanbay-crx#75]
网上有人反映从非chrome store下载的插件会导致chrome莫名其妙跳转天猫。 我排查了一下， 确实是这个插件导致的

**Comment by jinntrance** [comment]
你用Chrome Store 的版本安装了也会这样么？
https://chrome.google.com/webstore/detail/aibonellgbdkldghjgbnapgjblebfkbl

我也是用GitHub 上的直接发布到Chrome Store 的。两种方式应该一致。
如果确实会调整天猫，能方便查一下跳转天猫前的refer 么？ 有可能有些http 请求，域名被劫持然后跳转过去了。

**Comment by Andy1984** [comment]
关了吧， 是我搞错了， 我mac上的chrome有问题， 清缓存和删了重装都不行。 现在chrome不能上google， 之前会跳天猫和别的网址。 只好转firefox了

**Comment by jinntrance** [comment]
可以尝试清理一下Chrome 的DNS，以及把Chrome 的配置文件都删了重装 https://www.chromium.org/user-experience/user-data-directory 。我之前也有遇到这个问题，完全清理后重装就不会有这个问题了。
PS: Google 的服务，用Chrome 使用QUIC 协议会快很多。
