### ISSUE TITLE
对 PDF（In chrome） 中的单词无效解决思路

### ISSUE THREAD

**Issue by qins** [jinntrance/shanbay-crx#79]
PDF的selection探测可能比较麻烦。
换一种思路，“拷贝查词”。
就是ctrl+C，把词存入复制buffer里，插件就开始查单词。
不知容易实现不？

**Comment by jinntrance** [comment]
Chrome 打开 pdf ，是把 pdf 嵌在 html 里面的，只是默认不像正常网页那样能拿到 tab id ；所以目前消息传递过程中还无法传回展示单词意思。后续倒是可以看看看选中的，或者右键查词的解决方案。
