### ISSUE TITLE
弹出框插入位置

### ISSUE THREAD

**Issue by maicss** [jinntrance/shanbay-crx#80]
现在的规则好像是在页面的body下面添加弹出框，但是如果一个页面有很多嵌套的frame就很难看了。

能不能根据当前点击的元素寻找父级body再进行添加弹出框？

谢谢。

另外，我看你的源码，愣是没找到添加弹出框的代码在哪，能不能告知一下，谢谢了。

**Comment by maicss** [comment]
我找到了插入位置，我以为shanbay只是跟扇贝交互的代码呢

**Comment by jinntrance** [comment]
1. 回头我再加一些文档和说明，方便大家在这个基础上再开发。
2. 弹窗问题，之前也出现过好些问题。嵌 iframe、嵌 table 的，我是业余做这个扩展，也没找到特别好的办法。你要处理好了，再提一 PR 就最好不过了~

**Comment by maicss** [comment]
ok，等我PR
