### ISSUE TITLE
修改设置后保存成功，但再进入设置时又还原了

### ISSUE THREAD

**Issue by epsgerry02** [jinntrance/shanbay-crx#82]
╮(╯▽╰)╭

**Comment by jinntrance** [comment]
你是用的最新的 1.13.7.1 版本么？
 1.13.7 版本有这个问题。

**Comment by epsgerry02** [comment]
是1.13.7.1版本的= =

**Comment by XzAmrzs** [comment]
确实有这个问题！支持作者大大！尽快修改ＢＵＧ

**Comment by jinntrance** [comment]
我这面测试了好些 cases 都不能复现你们的问题。
你们能劳烦一下在设置页面点右键选择"Inspect"然后再看看有什么报错么？ @XzAmrzs @epsgerry02

**Comment by littleroad** [comment]
扇贝助手增强版 1.13.7.2/Google Chrome 版本 61.0.3159.5（正式版本）dev （64 位）

settings页面inspect发现如下报错log：
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: input[name=etym][value=]
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at ga.select (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at n.fn.init.find (jquery.min.js:2)
    at new n.fn.init (jquery.min.js:2)
    at n (jquery.min.js:2)
    at HTMLInputElement.<anonymous> (options.js:37)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
ga.error @ jquery.min.js:2
ga.tokenize @ jquery.min.js:2
ga.select @ jquery.min.js:2
ga @ jquery.min.js:2
find @ jquery.min.js:2
n.fn.init @ jquery.min.js:2
n @ jquery.min.js:2
(anonymous) @ options.js:37
each @ jquery.min.js:2
each @ jquery.min.js:2
restore_options @ options.js:33
(anonymous) @ options.js:88

如果需要更多信息，请联系我并告知获取方法

**Comment by jinntrance** [comment]
已修复 @littleroad 提到的这个问题。看目前是否正常了呢？ 1.13.7.3 版本

**Comment by littleroad** [comment]
扇贝助手增强版 1.13.7.3/Google Chrome 61.0.3163.13（正式版本）dev （64 位）已经修复了，可以正常保存设置

**Comment by epsgerry02** [comment]
13.7.3版本已恢复正常，感谢=3=
